Repository Raenore/Sippy-Cup, pull requests merged in 2025-06, with the labels that each got.

#10 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#11 Add X-Wago-ID for packager
  README.md
  SippyCup.toc
Labels: enhancement

#12 Make PRs create packager artifacts
  .github/workflows/pull_request.yml
Labels: enhancement

#13 Handle MainMenu errror on logout button
  .luacheckrc
  Modules/Popups/Popups.lua
  SippyCup.lua
Labels: bug

#17 Add MSP integrated "Only when IC" check
  .luacheckrc
  Core/Database.lua
  Locales/enUS.lua
  Locales/frFR.lua
  Modules/Popups/Popups.lua
  UI/ConfigPanel.lua
Labels: enhancement

#18 Only if IC expanded - checks all enabled consumables
  Core/Auras.lua
  Core/Database.lua
  SippyCup.lua
  UI/ConfigPanel.lua
Labels: enhancement

#16 Changelog - 0.1.1
  CHANGELOG.md
Labels: documentation

#21 Create ruRU.lua
  Locales/ruRU.lua
Labels: translations

#19 Fix MSP IC issues - test code better
  Core/Auras.lua
  Core/Utils.lua
  Modules/Popups/Popups.lua
  SippyCup.lua
Labels: bug

#20 Changelog - 0.1.2
  CHANGELOG.md
Labels: documentation

#23 IGNORE globalstring requires no translation
  Locales/ruRU.lua
Labels: bug, translations

#26 Changelog - 0.2.0
  CHANGELOG.md
  SippyCup.toc
Labels: documentation

#29 Fix loading screen, AuraMap and MisMatchDB issues
  Core/Auras.lua
  Core/Database.lua
  Init.lua
  SippyCup.lua
Labels: bug
